### ISSUE TITLE
安装后没有生成bin目录下的synch执行文件。找不到命令。

### ISSUE THREAD

**Issue by BiwenXiao** [long2ice/synch#16]
环境：centos 7, pip version = 20.1.1  ,  python -V = 3.6.5
pip install synch[all]后没有生成bin目录下的synch执行文件。所有依赖安装好了的。

**Comment by long2ice** [comment]
安装的版本是多少

**Comment by BiwenXiao** [comment]
我是直接执行pip install synch[all], 应该是最新版本吧。

**Comment by long2ice** [comment]
你直接克隆dev分支然后用docker试试

**Comment by BiwenXiao** [comment]
好
