### ISSUE TITLE
How to install pip using the dev version?

### ISSUE THREAD

**Issue by ericchuawc** [long2ice/synch#17]
HI there,

Like to install pip for the dev version.

I don't want to use docker.

Any help? Thanks.

**Comment by long2ice** [comment]
You can install by run `pip install -e git+https://github.com/long2ice/synch.git@dev#egg=synch`

**Comment by long2ice** [comment]
Or just install from `pip install synch`, which is latest.

**Comment by ericchuawc** [comment]
I tried this

`pip install synch`

and got this error

`Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-dXOXcr/synch/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-19ENRL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-dXOXcr/synch/
`
I am using python 2.7.5

**Comment by ericchuawc** [comment]
Tried this

`pip install -e git+https://github.com/long2ice/synch.git@dev#egg=synch`

and get this

`[root@localhost test]# pip install -e git+https://github.com/long2ice/synch.git@dev#egg=synch
Obtaining synch from git+https://github.com/long2ice/synch.git@dev#egg=synch
  Cloning https://github.com/long2ice/synch.git (to dev) to ./src/synch
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/root/test/src/synch/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /root/test/src/synch/`

**Comment by long2ice** [comment]
`synch` doesn't support `python2`

**Comment by ericchuawc** [comment]
I tried this in Centos 7 server

```
yum install -y python3
yum install postgresql-devel -y
pip3 install psycopg2-binary
pip3 install synch
```

But I get this, hmm...

```
    copying lib/_json.py -> build/lib.linux-x86_64-3.6/psycopg2
    copying lib/errors.py -> build/lib.linux-x86_64-3.6/psycopg2
    copying lib/compat.py -> build/lib.linux-x86_64-3.6/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/psycopg
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSYCOPG_VERSION=2.8.5 (dt dec pq3 ext) -DPG_VERSION_NUM=90224 -I/usr/include/python3.6m -I. -I/usr/include -I/usr/include/pgsql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.6/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:28:0:
    ./psycopg/psycopg.h:35:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    error: command 'gcc' failed with exit status 1

```
If I type gcc command

```
gcc: fatal error: no input files
compilation terminated.
```

Any idea? Thanks.

**Comment by long2ice** [comment]
You can google `Python.h: No such file or directory` and you will get answer.

**Comment by ericchuawc** [comment]
thanks, this works

`yum install python3-devel`
