### ISSUE TITLE
synch used for real time crud updates?

### ISSUE THREAD

**Issue by ericchuawc** [long2ice/synch#20]
I noticed in the synch.yaml

```
insert_num: 1 # how many num to submit,recommend set 20000 when production
insert_interval: 1 # how many seconds to submit,recommend set 60 when production
```

Why can't production, I set both as 1? If i set the interval to 60, it won't be real time or near real time updates?

Same to insert_num, it seems in production after hitting 20,000 records will get the updates. 

If I maintain 1 for both settings in production, will the program crashed?

**Comment by long2ice** [comment]
Because the delete and insert performance of ClickHouse is not so good, you can set that depends your business.
