### ISSUE TITLE
tuple(values[pk[i]] for i in pk) 问题

### ISSUE THREAD

**Issue by imysm** [long2ice/synch#21]
merge_tree.py line 80
这个地方 tuple(values[pk[i]] for i in pk)   是不是要改成下面的？
tuple(values[i] for i in pk)

**Comment by long2ice** [comment]
嗯，是的，我改了，你再更新看看

**Comment by imysm** [comment]
ok 好了

**Comment by long2ice** [comment]
嗯，可以加QQ群一起交流
