### ISSUE TITLE
运行时是否会有字符集问题？

### ISSUE THREAD

**Issue by huangyux1025** [long2ice/synch#22]
命令：synch --alias mysql_db etl --schema flink_t --table sych --renew 

错误：ImportError: cannot import name 'charset_to_encoding' from 'pymysql.charset' (/usr/local/python3/lib/python3.7/site-packages/pymysql/charset.py)

**Comment by long2ice** [comment]
这是mysql-replication这个包的问题，该包已经不怎么维护了，你从[https://github.com/long2ice/python-mysql-replication.git@pymysql_0_10_0](https://github.com/long2ice/python-mysql-replication.git@pymysql_0_10_0)更新一下该包就行了。

**Comment by huangyux1025** [comment]
> 这是mysql-replication这个包的问题，​​该包已经不怎么维护了，你从https://github.com/long2ice/python-mysql-replication.git@pymysql_0_10_0更新一下该包就行了。

试一下 Requirement already satisfied: PyMySQL in /usr/local/python3/lib/python3.7/site-packages (0.10.0)
这个包 就是最新的了 还是同样问题

**Comment by long2ice** [comment]
卸载重装mysql-replication

**Comment by huangyux1025** [comment]
Successfully installed mysql-replication-0.21
不行，服务器都重启了，还是这个同样的错误 
  File "/usr/local/python3/lib/python3.7/site-packages/pymysqlreplication/row_event.py", line 9, in <module>
    from pymysql.charset import charset_to_encoding
ImportError: cannot import name 'charset_to_encoding' from 'pymysql.charset' (/usr/local/python3/lib/python3.7/site-packages/pymysql/charset.py)

**Comment by long2ice** [comment]
从源码安装

**Comment by huangyux1025** [comment]
> 从源码安装

还是不行

**Comment by long2ice** [comment]
那你直接使用docker吧
