### ISSUE TITLE
clickhouse sql 错误

### ISSUE THREAD

**Issue by yufeikang** [long2ice/synch#24]
`- synch.replication.clickhouse:57 - DEBUG - alter table sheme.table delete where id in (xxxxx)`

主键id是string
正确的sql应该是 alter table epsandbox.q_order delete where id in (‘xxxxx’)

**Comment by yufeikang** [comment]
https://github.com/long2ice/synch/blob/5051276053b62ec37e59ef1ce6f61064f2affcec/synch/writer/merge_tree.py#L32

**Comment by long2ice** [comment]
你的主键是string类型的？

**Comment by yufeikang** [comment]
@long2ice 是的,主键string不是也是挺常见的吗🤦‍♂️

**Comment by long2ice** [comment]
嗯，不过当前没有支持，我自己一般用自增主键
