### ISSUE TITLE
MySQL同步到Clickhouse数据问题（Mysql bit类型）

### ISSUE THREAD

**Issue by sun642514265** [long2ice/synch#37]
mysql bit类型数据 无法同步到clickhouse。

**Comment by sun642514265** [comment]
![1](https://user-images.githubusercontent.com/54477096/99506025-882a5c00-29bc-11eb-8799-f9af4b143154.png)

**Comment by long2ice** [comment]
估计需要上游支持

**Comment by sun642514265** [comment]
哦，明白了，多谢大神！
