### ISSUE TITLE
pymysql.util 依赖问题

### ISSUE THREAD

**Issue by anafin** [long2ice/synch#45]
File "/opt/app/python3/clickhouse_synch/lib/python3.9/site-packages/pymysqlreplication/binlogstream.py", line 9, in <module>
    from pymysql.util import int2byte
ModuleNotFoundError: No module named 'pymysql.util

**Comment by anafin** [comment]
您好，请问需要安装什么才能满足依赖？

**Comment by long2ice** [comment]
试试旧版本的pymysqlreplication，我这边这项目也没怎么使用跟维护了

**Comment by anafin** [comment]
感谢！
mysql与clickhouse的同步，对比了多个，只有你这个最靠谱，如果不维护了，有其他项目推荐么？

**Comment by long2ice** [comment]
好像没有，之前也是因为没找到合适的才自己写了个，你可以看看clickhouse自带的https://clickhouse.tech/docs/en/engines/database-engines/materialize-mysql/
