### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by han-xuefeng** [long2ice/synch#58]
![image](https://user-images.githubusercontent.com/12689759/133740443-7d102a67-b46f-4023-81a5-4ffb813fb1d7.png)
不管指定了配置文件，还是没有指定配置文件，都是这个错误。
安装最新的版本是这个错误，手动编译了0.65版本也是这个错误。python3.8

**Comment by long2ice** [comment]
最新是0.7.1

**Comment by han-xuefeng** [comment]
是我哪里操作错误了吗？  还是我的python版本有问题。

**Comment by han-xuefeng** [comment]
我第一次pip insyall 安装的最新的  报了这个错误
然后我有编译了0.65 也是报这个错误
是我的环境的问题吗？

**Comment by long2ice** [comment]
先卸载老的再编译安装试试

**Comment by han-xuefeng** [comment]
![image](https://user-images.githubusercontent.com/12689759/133750330-f6913712-8113-4ce1-8fd0-509eafdc8bfa.png)
最新的不行，

**Comment by han-xuefeng** [comment]
卸载最新的 编译老的也不行。

**Comment by long2ice** [comment]
clone 最新源码安装试试，sentry那个选项没有了

**Comment by han-xuefeng** [comment]
![image](https://user-images.githubusercontent.com/12689759/133766669-bd1721f8-207e-41c0-9f75-4cef6788c646.png)
git clone 最新的代码  dev分支，编译安装。可用。感谢。非常感谢
