### ISSUE TITLE
mysql到clickhouse

### ISSUE THREAD

**Issue by Phoebus888** [long2ice/synch#63]
mysql的update和delete也对应clickhouse端的update和delete吗

**Comment by long2ice** [comment]
是的

**Comment by Phoebus888** [comment]
这个使用的方式就是
1、先手动etl全量同步     使用synch --alias mysql_db etl --schema test --table test --table test2
2、监听mysql_binlog到produce  使用synch --alias mysql_db produce
3、处理消息到clickhouse   使用synch --alias mysql_db consume --schema test
