### ISSUE TITLE
运行mysql2ch produce 出错

### ISSUE THREAD

**Issue by BiwenXiao** [long2ice/synch#8]
按照您的最新配置文件，
mysql_server_id = 1
init_binlog_file = binlog.000088
init_binlog_pos = 2238

运行produce报错：
 File "/usr/local/bin/mysql2ch", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/cli.py", line 66, in cli
    parse_args.run(parse_args)
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/cli.py", line 27, in run
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/producer.py", line 43, in produce
    skip_update_tables=settings.skip_update_tables,
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/reader.py", line 93, in binlog_reading
    for binlog_event in stream:
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 430, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1236, 'Could not find first log file name in binary log index file')

请求帮助！

**Comment by long2ice** [comment]
你需要设置mysql的binglog配置，不能用配置文件自带的，在mysql执行：
```sql
show master status
```

**Comment by BiwenXiao** [comment]
只需要改一下ini文件吗？需要刷新么，我改了之后新的配置没有起作用。需要重启吗？

**Comment by long2ice** [comment]
需要重启

**Comment by BiwenXiao** [comment]
能不能支持从多个不同数据库同步表啊？
我这个是在服务器上面，重启机器不可以的。

**Comment by BiwenXiao** [comment]
我以前的版本要更新到最新有什么办法吗？

**Comment by long2ice** [comment]
重启mysql2ch不是重启机器，不同数据库实例建立多个配置文件

**Comment by BiwenXiao** [comment]
mysql2ch 没有重启命令啊，只有etl，produce，consume

**Comment by long2ice** [comment]
你可以记录binlog位置，升级mysql2ch，修改配置，然后从最新binlog同步。

**Comment by long2ice** [comment]
就是把进程杀了然后重新启动

**Comment by BiwenXiao** [comment]
谢谢，我先去试试

**Comment by BiwenXiao** [comment]
这个进程名字是啥啊，我找了所有进程找不到看起来像的。

**Comment by long2ice** [comment]
你用什么启动的？

**Comment by BiwenXiao** [comment]
直接命令mysql2ch etl --schema

**Comment by long2ice** [comment]
这是全量同步，执行了就完了，没有后台进程

**Comment by BiwenXiao** [comment]
那为啥改了配置文件不生效啊

**Comment by long2ice** [comment]
你需要什么生效？

**Comment by BiwenXiao** [comment]
mysql_server_id = 1
init_binlog_file = mysql-bin.000002
init_binlog_pos = 271943925

**Comment by BiwenXiao** [comment]
这是我之前按照模板来的
2020-06-11 16:06:06 - mysql2ch.producer:26 - INFO - start producer success!
2020-06-11 16:06:06 - mysql2ch.reader:76 - INFO - start sync at 2020-06-11 16:06:06
2020-06-11 16:06:06 - mysql2ch.reader:77 - INFO - mysql binlog: binlog.000088:2238
Traceback (most recent call last):
  File "/usr/local/bin/mysql2ch", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/cli.py", line 66, in cli
    parse_args.run(parse_args)
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/cli.py", line 27, in run
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/producer.py", line 43, in produce
    skip_update_tables=settings.skip_update_tables,
  File "/usr/local/lib/python3.6/site-packages/mysql2ch/reader.py", line 93, in binlog_reading
    for binlog_event in stream:
  File "/usr/local/lib/python3.6/site-packages/pymysqlreplication/binlogstream.py", line 430, in fetchone
    pkt = self._stream_connection._read_packet()
  File "/usr/local/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet

**Comment by BiwenXiao** [comment]
配置文件我已经换了一个了，然后还换了个位置，依然没有作用

**Comment by long2ice** [comment]
这好像是权限的问题

**Comment by BiwenXiao** [comment]
我一直是root运行的

**Comment by long2ice** [comment]
mysql账号

**Comment by BiwenXiao** [comment]
我的全量导入已经成功了。
这个binlog运行的时候没有用我最新的配置， 我的是mysql-bin00002

**Comment by long2ice** [comment]
要先清空redis里面的

**Comment by BiwenXiao** [comment]
我去试试

**Comment by BiwenXiao** [comment]
删除缓存，更改配置文件成功，还是报之前那个错误！连接数据库问题吗？

**Comment by long2ice** [comment]
应该是你的mysql账号没有同步权限

**Comment by BiwenXiao** [comment]
好的，我去瞅瞅，真的太感谢了。已star

**Comment by BiwenXiao** [comment]
root没有同步权限吗？还有这操作

**Comment by long2ice** [comment]
你检查下mysql2ch.ini中mysql相关配置

**Comment by BiwenXiao** [comment]
配置有问题，全量导入应该会失败吧

**Comment by long2ice** [comment]
报错就是报的读不到binlog

**Comment by BiwenXiao** [comment]
好的。。

**Comment by BiwenXiao** [comment]
请教一下，工程的本地调试在哪儿启动啊，刚刚下载了工程，搞了个pycharm，没用过。

**Comment by long2ice** [comment]
先用poetry安装依赖，执行``python -m mysql2ch.cli consume --schema test``启动

**Comment by zhechu** [comment]
官方 docker-compose.yml 配置的 Redis 有问题，单独部署就解决了

version: '3'
services:
  producer:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db produce
    volumes:
      - ./synch.yaml:/synch/synch.yaml
  # one service consume on schema
  consumer.user:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db consume --schema user
    volumes:
      - ./synch.yaml:/synch/synch.yaml
#  redis:
#    image: redis:latest
#    volumes:
#      - redis:/data
#volumes:
#  redis:

**Comment by zhechu** [comment]
官方 docker-compose.yml 配置的 Redis 有问题，单独部署就解决了

`version: '3'
services:
  producer:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db produce
    volumes:
      - ./synch.yaml:/synch/synch.yaml
  # one service consume on schema
  consumer.doraemon_user:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db consume --schema doraemon_user
    volumes:
      - ./synch.yaml:/synch/synch.yaml
#  redis:
#    image: redis:latest
#    volumes:
#      - redis:/data
#volumes:
#  redis:
`

**Comment by zhechu** [comment]
官方 docker-compose.yml 配置的 Redis 有问题，单独部署就解决了

```shell
version: '3'
services:
  producer:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db produce
    volumes:
      - ./synch.yaml:/synch/synch.yaml
  # one service consume on schema
  consumer.doraemon_user:
#    depends_on:
#      - redis
    image: long2ice/synch
    command: synch --alias mysql_db consume --schema doraemon_user
    volumes:
      - ./synch.yaml:/synch/synch.yaml
#  redis:
#    image: redis:latest
#    volumes:
#      - redis:/data
#volumes:
#  redis:
```

**Comment by long2ice** [comment]
有报错吗

**Comment by zhechu** [comment]
事实上是Redis缓存的问题，若第一次运行报错，则Redis会缓存Mysql bin log 信息，而用 Docker 部署，若Redis数据卷未删除，只删除容器重新部署，那缓存是还在的，Redis重新部署时，缓存会从数据卷的磁盘读入。

**Comment by long2ice** [comment]
好的
