### ISSUE TITLE
运行mysql2ch etl -h没有反应

### ISSUE THREAD

**Issue by shuiyueqingnong** [long2ice/synch#9]
[root@localhost bin]# mysql2ch etl -h
usage: mysql2ch etl [-h] --schema SCHEMA [--tables TABLES] [--renew]

optional arguments:
  -h, --help       show this help message and exit
  --schema SCHEMA  Schema to full etl.
  --tables TABLES  Tables to full etl,multiple tables split with comma,default
                   read from environment.
  --renew          Etl after try to drop the target tables.

配置文件：

[core]
mysql_server_id = 1
# redis stream max len, will delete redundant ones with FIFO
queue_max_len = 200000
init_binlog_file = binlog.000024
init_binlog_pos = 252563
# these tables skip delete,multiple separated with comma
skip_delete_tables =
# these tables skip update,multiple separated with comma
skip_update_tables =
# skip delete or update dmls,multiple separated with comma
skip_dmls =
# how many num to submit,recommend set 20000 when production
insert_num = 1
# how many seconds to submit,recommend set 60 when production
insert_interval = 1

[sentry]
# sentry environment
environment = development
# sentry dsn
dsn = https://xxxxxxxx@sentry.test.com/1

[redis]
host = 127.0.0.1
port = 6379
password =
db = 0
prefix = mysql2ch
# enable redis sentinel
sentinel = false
# redis sentinel hosts,multiple separated with comma
sentinel_hosts = 127.0.0.1:5000,127.0.0.1:5001,127.0.0.1:5002
sentinel_master = master

[mysql]
host = 127.0.0.1
port = 3306
user = root
password =

# sync schema test from mysql
[mysql.saas_im]
# multiple separated with comma
tables = letter_record_back

[clickhouse]
host = 127.0.0.1
port = 9000
user = default
password =

**Comment by long2ice** [comment]
需要啥子反应？``mysql2ch etl -h`` 是查询用法的

**Comment by shuiyueqingnong** [comment]
> 需要啥子反应？`mysql2ch etl -h` 是查询用法的

请问一下，这个从mysql导入clickhouse具体要怎么操作？  刚开始用clickhouse，不太熟，麻烦了

**Comment by long2ice** [comment]
先完善配置文件，然后先执行全量导入，再执行生产者和消费者守护进程，你可以先详细看看文档。

**Comment by shuiyueqingnong** [comment]
> 先完善配置文件，然后先执行全量导入，再执行生产者和消费者守护进程，你可以先详细看看文档。

好的，谢谢
